# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SayKit Developer Preview
email: info@saykit.org
description: > # this means to ignore newlines until "baseurl:"
  SayKit SDK: Everything you expect from a UI Framework, dedicated to speech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://developer.saykit.org" # the base hostname & protocol for your site
twitter_username: ConversantLabs
github_username:  ConversantLabs

# Build settings
markdown: kramdown
kramdown:
  input: GFM
